# Baseline experiment 

the output of the first assessment of a pair is used as predicton for the second assessment.

In [1]:
from constants import targets, get_feature_sets
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectKBest, chi2, RFE
from sklearn.model_selection import train_test_split, cross_validate, KFold, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import SimpleImputer, KNNImputer, IterativeImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, FunctionTransformer
from sklearn.ensemble import ExtraTreesClassifier, HistGradientBoostingClassifier
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.compose import ColumnTransformer

X = pd.read_pickle('data/cached_X_imputed.pckl')
y = pd.read_pickle('data/cached_y.pckl')
feature_sets = get_feature_sets(X)
df = pd.read_pickle('data/cached_df.pckl')

ys_train, ys_test = [], []
lastrow = None

patient_ids = df.BALANCE_ID.unique()
for patient_id in patient_ids:
    pdf = df[df.BALANCE_ID == patient_id]
    for i in range(0, pdf.shape[0] - 1):
        for j in range(i+1, pdf.shape[0]):
            assessment0 = pdf.iloc[i].copy()
            assessment1 = pdf.iloc[j]
            
            time_diff = assessment1['Assessment_date_days'] - assessment0['Assessment_date_days']
            assessment0['time_diff'] = time_diff;
            
            # THIS IS THE ONLY CHANGE IN THIS NOTEBOOK COMPARED TO COMMON PREPROCESSING.
            ys_train.append(assessment0[['BALANCE_ID'] + targets])
            ys_test.append(assessment1[['BALANCE_ID'] + targets])

In [2]:
# Convert to DataFrames
y_train = pd.DataFrame(ys_train).reset_index(drop=True)
y_test = pd.DataFrame(ys_test).reset_index(drop=True)

### Last Observation Carried Forward (LOCF) baseline which assumes that T0==T1 WITHOUT a prediction model

In [3]:
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.utils import resample
import numpy as np
import matplotlib.pyplot as plt

results_LOCF = {}
n_bootstraps = 1000
rng = np.random.RandomState(42)  # For reproducibility

for target in targets:
    # Extract true labels and predicted probabilities for the target
    true_labels = y_test[target].astype(int)
    predicted_scores = y_train[target].astype(float)  # LOCF assumption

    # Calculate the base AUC
    auc_value = roc_auc_score(true_labels, predicted_scores)

    # Bootstrap AUCs
    bootstrapped_scores = []
    for i in range(n_bootstraps):
        # Bootstrap sample indices
        indices = rng.randint(0, len(predicted_scores), len(predicted_scores))
        if len(np.unique(true_labels.iloc[indices])) < 2:
            continue  # Skip if only one class in sample
        auc = roc_auc_score(true_labels.iloc[indices], predicted_scores.iloc[indices])
        bootstrapped_scores.append(auc)

    # Compute 95% confidence interval
    ci_lower, ci_upper = np.percentile(bootstrapped_scores, [2.5, 97.5])

    # Store results
    results_LOCF[target] = {
        "Classifier": "LOCF",
        "roc_auc": {
            "mean": auc_value,
            "95% CI": (ci_lower, ci_upper)
        }
    }

    print(f"{target} - ROC AUC: {auc_value:.3f} (95% CI: {ci_lower:.3f} - {ci_upper:.3f})")

C30_PF2_class - ROC AUC: 0.761 (95% CI: 0.757 - 0.765)
C30_RF2_class - ROC AUC: 0.692 (95% CI: 0.687 - 0.697)
C30_EF_class - ROC AUC: 0.704 (95% CI: 0.700 - 0.708)
C30_CF_class - ROC AUC: 0.744 (95% CI: 0.740 - 0.747)
C30_SF_class - ROC AUC: 0.690 (95% CI: 0.683 - 0.697)
C30_FA_class - ROC AUC: 0.708 (95% CI: 0.704 - 0.713)
C30_NV_class - ROC AUC: 0.646 (95% CI: 0.641 - 0.651)
C30_PA_class - ROC AUC: 0.700 (95% CI: 0.695 - 0.703)
C30_DY_class - ROC AUC: 0.720 (95% CI: 0.716 - 0.724)
C30_SL_class - ROC AUC: 0.681 (95% CI: 0.676 - 0.685)
C30_AP_class - ROC AUC: 0.620 (95% CI: 0.610 - 0.629)
C30_CO_class - ROC AUC: 0.671 (95% CI: 0.663 - 0.679)
C30_DI_class - ROC AUC: 0.642 (95% CI: 0.637 - 0.647)
C30_FI_class - ROC AUC: 0.759 (95% CI: 0.753 - 0.764)

In [30]:
rows = []

for target, metrics in results_LOCF.items():
    row = {
        'Target': target,
        'Classifier': metrics['Classifier']
    }

    if 'roc_auc' in metrics:
        roc_auc = metrics['roc_auc']
        row['roc_auc'] = round(roc_auc['mean'], 3)
        row['roc_auc_ci_low'] = round(roc_auc['95% CI'][0], 3)
        row['roc_auc_ci_high'] = round(roc_auc['95% CI'][1], 3)

    rows.append(row)

# Create DataFrame
results_df = pd.DataFrame(rows)

# Display
display(results_df)

# Export to CSV
results_df.to_csv('results_LOCF_AUC.csv', index=False)

           Target Classifier  roc_auc  roc_auc_ci_low  roc_auc_ci_high
0    C30_FA_class       LOCF    0.708           0.704            0.713
1    C30_PA_class       LOCF    0.700           0.696            0.704
2    C30_NV_class       LOCF    0.646           0.640            0.651
3    C30_SL_class       LOCF    0.681           0.676            0.685
4    C30_DY_class       LOCF    0.720           0.716            0.724
5    C30_AP_class       LOCF    0.620           0.610            0.630
6    C30_CO_class       LOCF    0.671           0.662            0.678
7    C30_DI_class       LOCF    0.642           0.637            0.647
8    C30_FI_class       LOCF    0.759           0.754            0.764
9   C30_PF2_class       LOCF    0.761           0.758            0.765
10  C30_RF2_class       LOCF    0.692           0.687            0.697
11   C30_SF_class       LOCF    0.690           0.683            0.697
12   C30_EF_class       LOCF    0.704           0.700            0.709
13   C30_CF_class       LOCF    0.744           0.740            0.747

In [11]:
assert X.shape[0] == y_train.shape[0] == y_test.shape[0]

# Baseline using univariate logistic regression

In [17]:
import pickle
import pandas as pd

test_data_predictors = pd.read_pickle('data/external_x.pckl')
test_data_targets = pd.read_csv('data/targets_external.csv')

In [18]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

results_lr = {}
n_bootstraps = 1000
rng = np.random.RandomState(42)

# External validation data
test_data_predictors = pd.read_pickle('data/external_x.pckl')
test_data_targets = pd.read_csv('data/targets_external.csv')

# Baseline logistic regression
logreg = LogisticRegression(
    penalty=None,
    solver="lbfgs",
    max_iter=1000
)

baseline_predictors = {
     'C30_PF2_class': ["C30_PF2", "time_diff"],
     'C30_RF2_class': ["C30_RF2","time_diff"],
     'C30_EF_class': ["C30_EF", "time_diff"],
     'C30_CF_class': ["C30_CF","time_diff"],
     'C30_SF_class': ["C30_SF","time_diff"],
     'C30_FA_class': ["C30_FA","time_diff"],
     'C30_NV_class': ["C30_NV","time_diff"],
     'C30_PA_class': ["C30_PA","time_diff"],
     'C30_DY_class': ["C30_DY","time_diff"],
     'C30_SL_class': ["C30_SL","time_diff"],
     'C30_AP_class': ["C30_AP","time_diff"],
     'C30_CO_class': ["C30_CO","time_diff"],
     'C30_DI_class': ["C30_DI","time_diff"],
     'C30_FI_class': ["C30_FI", "time_diff"]
 }

# Baseline logistic regresssion

for target, predictors in baseline_predictors.items():

    print(f"Processing target: {target}")

    # ---------- TRAIN ----------
    X_train = X[predictors]
    y_train = y[target].astype(int)

    model = logreg.fit(X_train, y_train)

    # ---------- TEST ----------
    X_test, y_test = (
    test_data_predictors[predictors]
    .join(test_data_targets[target])
    .dropna()
    .pipe(lambda df: (df[predictors], df[target].astype(int).values))
    )

    predicted_scores = model.predict_proba(X_test)[:, 1]

    # Base ROC AUC
    auc_value = roc_auc_score(y_test, predicted_scores)

    # ---------- BOOTSTRAP CI ----------
    bootstrapped_scores = []

    n_samples = len(predicted_scores)
    for _ in range(n_bootstraps):
        indices = rng.randint(0, n_samples, n_samples)

        if len(np.unique(y_test[indices])) < 2:
            continue

        auc = roc_auc_score(
            y_test[indices],
            predicted_scores[indices]
        )
        bootstrapped_scores.append(auc)

    ci_lower, ci_upper = np.percentile(bootstrapped_scores, [2.5, 97.5])

    # ---------- STORE RESULTS ----------
    results_lr[target] = {
        "Classifier": "Baseline LR",
        "roc_auc": {
            "mean": auc_value,
            "95% CI": (ci_lower, ci_upper)
        }
    }

    print(
        f"{target} - ROC AUC: {auc_value:.3f} "
        f"(95% CI: {ci_lower:.3f}–{ci_upper:.3f})"
    )

Processing target: C30_PF2_class
C30_PF2_class - ROC AUC: 0.759 (95% CI: 0.730–0.791)
Processing target: C30_RF2_class
C30_RF2_class - ROC AUC: 0.696 (95% CI: 0.659–0.734)
Processing target: C30_EF_class
C30_EF_class - ROC AUC: 0.765 (95% CI: 0.737–0.792)
Processing target: C30_CF_class
C30_CF_class - ROC AUC: 0.752 (95% CI: 0.724–0.779)
Processing target: C30_SF_class
C30_SF_class - ROC AUC: 0.689 (95% CI: 0.646–0.733)
Processing target: C30_FA_class
C30_FA_class - ROC AUC: 0.715 (95% CI: 0.685–0.742)
Processing target: C30_NV_class
C30_NV_class - ROC AUC: 0.684 (95% CI: 0.643–0.720)
Processing target: C30_PA_class
C30_PA_class - ROC AUC: 0.648 (95% CI: 0.616–0.679)
Processing target: C30_DY_class
C30_DY_class - ROC AUC: 0.707 (95% CI: 0.678–0.739)
Processing target: C30_SL_class
C30_SL_class - ROC AUC: 0.734 (95% CI: 0.700–0.766)
Processing target: C30_AP_class
C30_AP_class - ROC AUC: 0.829 (95% CI: 0.767–0.884)
Processing target: C30_CO_class
C30_CO_class - ROC AUC: 0.783 (95% CI: 0.727–0.833)
Processing target: C30_DI_class
C30_DI_class - ROC AUC: 0.660 (95% CI: 0.616–0.699)
Processing target: C30_FI_class
C30_FI_class - ROC AUC: 0.725 (95% CI: 0.684–0.770)

In [19]:
rows = []

for target, metrics in results_lr.items():
    row = {
        'Target': target,
        'Classifier': metrics['Classifier']
    }

    if 'roc_auc' in metrics:
        roc_auc = metrics['roc_auc']
        row['roc_auc'] = round(roc_auc['mean'], 3)
        row['roc_auc_ci_low'] = round(roc_auc['95% CI'][0], 3)
        row['roc_auc_ci_high'] = round(roc_auc['95% CI'][1], 3)

    rows.append(row)

# Create DataFrame
results_df = pd.DataFrame(rows)

# Display
display(results_df)

# Export to CSV
results_df.to_csv('results_lr_AUC.csv', index=False)

           Target   Classifier  roc_auc  roc_auc_ci_low  roc_auc_ci_high
0   C30_PF2_class  Baseline LR    0.759           0.730            0.791
1   C30_RF2_class  Baseline LR    0.696           0.659            0.734
2    C30_EF_class  Baseline LR    0.765           0.737            0.792
3    C30_CF_class  Baseline LR    0.752           0.724            0.779
4    C30_SF_class  Baseline LR    0.689           0.646            0.733
5    C30_FA_class  Baseline LR    0.715           0.685            0.742
6    C30_NV_class  Baseline LR    0.684           0.643            0.720
7    C30_PA_class  Baseline LR    0.648           0.616            0.679
8    C30_DY_class  Baseline LR    0.707           0.678            0.739
9    C30_SL_class  Baseline LR    0.734           0.700            0.766
10   C30_AP_class  Baseline LR    0.829           0.767            0.884
11   C30_CO_class  Baseline LR    0.783           0.727            0.833
12   C30_DI_class  Baseline LR    0.660           0.616            0.699
13   C30_FI_class  Baseline LR    0.725           0.684            0.770